baseURL = "https://diapraesentation.projektemacher.org/"
languageCode = "de"
title = "Diapräsentation"
description = "Diaprojektor statt PowerPoint"
publishDir = "docs"
canonifyurls = true
disableKinds = ["term", "taxonomy"]
languagecode = "de"
defaultcontentlanguage = "de"
enableGitInfo = true
theme = "observer-hugo"

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über"
        weight = 2
        url = "about/"

[markup.goldmark.renderer]
    unsafe= true

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/pdfjs-dist"
        target = "static/js/pdfjs"
