baseURL = "http://example.org/"
languageCode = "de"
title = "Diapräsentation"
description = "Diaprojektor statt PowerPoint"
publishDir = "docs"
canonifyurls = true
disableKinds = ["term", "taxonomy"]
languagecode = "de"
defaultcontentlanguage = "de"

[menu]
    [[menu.main]]
        name = "Home"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "About"
        weight = 2
        url = "about/"


[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/css"
        target = "assets/css"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/jquery/dist"
        target = "assets/js/jquery"
